spring:
  cloud:
    stream:
      bindings:
        inboundOrgChanges:
          destination: orgChangeTopic
          content-type: application/json
          group: licensingGroup
        binder:
          zkNodes: localhost
          brokers: localhost

security:
  oauth2:
    client:
      client-id: eagleeye
      client-secret: thisissecret
      access-token-uri: http://localhost:8901/oauth/token/
    resource:
      userInfoUri: http://localhost:8901/user



eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

#Setting logging leveks
logging:
  level:
    com.netflix: warn
    org.springframework.web: warn
    com.filip: debug

server:
  port: 8082

