server:
  port: 8083

#Setting logging leveks
logging:
  level:
    com.netflix: warn
    org.springframework.web: warn
    com.filip: debug

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
