
#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.filip: DEBUG

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8901

#server:
#  contextPath:   /auth

spring:
  jpa:
    show-sql: true
    #hibernate:
      #ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        dialect: "org.hibernate.dialect.MySQL5Dialect"
    generate-ddl: true
  datasource:
    platform: "mysql"
    url: "jdbc:mysql://localhost:3306/db_example?useSSL=false"
    username: root
    password: secret

redis:
  server: "redis"
  port: "6379"

signing:
  key: "345345fsdfsf5345"