spring:
  cloud:
    stream:
      bindings:
        output:
          destination: orgChangeTopic
          content-type: application/json
        kafka:
          binder:
            zkNodes: localhost
            brokers: localhost

#Setting the logging levels for the service
logging:
  level:
    com.netflix: warn
    org.springframework.web: warn
    com.filip: debug

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
server:
  port: 8085
